# Generated by Django 3.1.2 on 2021-05-30 18:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('plot', models.TextField(blank=True, null=True, verbose_name='Plot')),
                ('release_date', models.DateField(blank=True, help_text='Please use the following format: <em>YYYY-MM-DD</em>.', null=True, verbose_name='Release date')),
                ('lenght', models.IntegerField(blank=True, help_text='Please enter an integer value (minutes)', null=True, verbose_name='Lenght')),
                ('rate', models.FloatField(default=5.0, help_text='Please enter an float value (range 1.0 - 10.0)', null=True, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='Rating')),
                ('genres', models.ManyToManyField(help_text='Select a genre for this song', to='music.Genre')),
            ],
            options={
                'ordering': ['-release_date', 'title', 'rate'],
            },
        ),
    ]
