# Generated by Django 3.1.2 on 2021-06-09 14:01

from django.db import migrations, models
import music.models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='poster',
        ),
        migrations.AddField(
            model_name='album',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to=music.models.poster_path, verbose_name='Album image'),
        ),
    ]
