# Generated by Django 3.1.2 on 2021-06-07 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='songs',
            field=models.ManyToManyField(help_text='Songs in album', to='music.Song'),
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('plot', models.TextField(blank=True, null=True, verbose_name='Playlist description')),
                ('song', models.ManyToManyField(help_text='Select songs for your playlist', to='music.Song')),
            ],
        ),
    ]
