# Generated by Django 3.1.2 on 2021-05-30 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='plot',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
