# Generated by Django 3.1.2 on 2021-06-07 18:35

from django.db import migrations, models
import music.models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_album_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to=music.models.poster_path, verbose_name='Album image'),
        ),
    ]
