# Generated by Django 3.1.2 on 2021-06-07 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_album_poster'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='lenght',
            new_name='length',
        ),
    ]
