# Generated by Django 3.1.2 on 2021-05-30 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20210530_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='length',
            field=models.FloatField(default=1.3, help_text='Please enter an float value (minutes, seconds)', verbose_name='Length'),
        ),
    ]
