# Generated by Django 3.1.2 on 2021-05-30 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_auto_20210530_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='length',
        ),
        migrations.AddField(
            model_name='song',
            name='lenght',
            field=models.IntegerField(blank=True, help_text='Please enter an integer value (minutes)', null=True, verbose_name='Lenght'),
        ),
    ]
