# Generated by Django 3.1.2 on 2021-06-06 12:33

from django.db import migrations, models
import music.models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_auto_20210606_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='album',
        ),
        migrations.AddField(
            model_name='song',
            name='albumcover',
            field=models.ImageField(blank=True, null=True, upload_to=music.models.album_path, verbose_name='Album Cover'),
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Album Title')),
                ('release_date', models.DateField(blank=True, help_text='Please use the following format: <em>YYYY-MM-DD</em>.', null=True, verbose_name='Release date')),
                ('songs', models.ManyToManyField(help_text='select the songs that belong to this album', to='music.Song')),
            ],
        ),
    ]
