# Generated by Django 3.1.2 on 2021-06-06 12:33

from django.db import migrations, models
import music.models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_auto_20210606_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='albumcover',
        ),
        migrations.AddField(
            model_name='album',
            name='albumcover',
            field=models.ImageField(blank=True, null=True, upload_to=music.models.album_path, verbose_name='Album Cover'),
        ),
    ]
